import mysql.connector

def create_tables(db):
    mycursor = db.cursor()
    mycursor.execute("DROP TABLE loan")
    mycursor.execute("DROP TABLE book")
    mycursor.execute("DROP TABLE title")
    mycursor.execute("DROP TABLE user")
    mycursor.execute("DROP TABLE library")
    mycursor.execute("DROP TABLE book_order")
    mycursor.execute("DROP TABLE offers")
    mycursor.execute("DROP TABLE voted")
    mycursor.execute("DROP TABLE waiting")

    mycursor.execute("CREATE TABLE library (l_id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(64) UNIQUE NOT NULL, address VARCHAR(64) NOT NULL, open VARCHAR(128))")
    mycursor.execute("CREATE TABLE user (u_id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(64) NOT NULL, last_name VARCHAR(64) NOT NULL, address VARCHAR(64), phone VARCHAR(64), birth DATE, username VARCHAR(64) UNIQUE NOT NULL, pwd VARCHAR(128) NOT NULL, role INT, l_id INT references library(l_id))")
    mycursor.execute("CREATE TABLE title (ISBN INT8 PRIMARY KEY, title_name VARCHAR(64), author VARCHAR(64), genre VARCHAR(64), rating FLOAT)")
    mycursor.execute("CREATE TABLE book (b_id INT AUTO_INCREMENT PRIMARY KEY, l_id int references library(l_id), ISBN INT references title(ISBN), active INT)")
    mycursor.execute("CREATE TABLE loan (ll_id INT AUTO_INCREMENT PRIMARY KEY, b_id int references book(b_id), u_id INT references user(u_id), d_from DATE, d_to DATE, l_id INT references library(l_id))")
    mycursor.execute("CREATE TABLE book_order (o_id INT AUTO_INCREMENT PRIMARY KEY, ISBN INT references title(ISBN), l_id INT references library(l_id), count INT)")
    mycursor.execute("CREATE TABLE offers (of_id INT AUTO_INCREMENT PRIMARY KEY, ISBN INT references title(ISBN), l_id INT references library(l_id), votes INT)")
    mycursor.execute("CREATE TABLE voted (v_id INT AUTO_INCREMENT PRIMARY KEY, ISBN INT references title(ISBN), l_id INT references library(l_id), u_id INT references user(u_id))") 
    mycursor.execute("CREATE TABLE waiting (w_id INT AUTO_INCREMENT PRIMARY KEY, ISBN INT references title(ISBN), l_id INT references library(l_id), u_id INT references user(u_id))")  

    mycursor.execute("insert into library(name,address,open) values('Trencin','Jaselská 2, Trencin','Po-Pia 7:00-17:00')")
    mycursor.execute("insert into library(name,address,open) values('Dubnica','Pionierska 396, Dubnica n/V','Po,St,Pia 7:00-15:00')")
    mycursor.execute("insert into library(name,address,open) values('Brno','Musilova 6, Brno','Po-Pa 7:00-17:00, So 8:00-12:00')")

    mycursor.execute("insert into user(name, last_name, address, phone, birth, username, pwd, role) values('Peter','Cmorik','Trencin 5','0905123123',DATE '1999-10-05', 'admin', '$2y$10$r4rkUev8.8J/2/yH4P5XRO1oJdRHupm7JRfK/RF9I/iF1MdIOyhIy', 3)")
    mycursor.execute("insert into user(name, last_name, address, phone, birth, username, pwd, role) values('Miro','Zbirka','Trencin 6','0905123456',DATE '1990-10-05', 'user', '$2y$10$M.eo9uBoAYVU.lS.y/RQ5eOnWd6QZEvqlgEYlZ0BbVnQppbXUatuy', 0)")
    mycursor.execute("insert into user(name, last_name, address, phone, birth, username, pwd, role, l_id) values('Jozo','Vajda','Purkynova 64','0905456456',DATE '1980-10-05', 'worker', '$2y$10$R87QD4fLSXzkRkeaoJ0h8uIe7.CyjhdKzguq.xJjmOqcsABxfUnDe', 1, 1)")
    mycursor.execute("insert into user(name, last_name, address, phone, birth, username, pwd, role) values('Riso','Muller','Trencin 8','0908123456',DATE '1985-10-05', 'distributor', '$2y$10$9UgvPCm5lc/lpDMgL5mcbefPuPViEaRFwvxHQyJc7oJ.WZxPmbydG', 2)")

    mycursor.execute("insert into title(ISBN,title_name,author,genre,rating) values(123,'Stoparov sprievodca','Douglas Adams','fantasy',4.5)")
    mycursor.execute("insert into title(ISBN,title_name,author,genre,rating) values(135,'Vinnetou','Karl May','western',4.20)")
    mycursor.execute("insert into title(ISBN,title_name,author,genre,rating) values(136,'Vinnetou2','Karl May','western',4.10)")
    mycursor.execute("insert into title(ISBN,title_name,author,genre,rating) values(555,'Zabijak','Dominik Dan','detektivka',3.90)")
    mycursor.execute("insert into title(ISBN,title_name,author,genre,rating) values(333,'Laska moja','Andrej Sladkovic','romanticka',2.50)")
    mycursor.execute("insert into title(ISBN,title_name,author,genre,rating) values(331,'Ako vysvetlit svet','Steven Weinberg','vzdelávanie',3.60)")
    mycursor.execute("insert into title(ISBN,title_name,author,genre,rating) values(332,'Die Grundlehren der Hoheren Analysis','Dr. Julius Wenck','vzdelávanie',2.50)")
    mycursor.execute("insert into title(ISBN,title_name,author,genre,rating) values(334,'Metro2033','Dmitrij Gluchovskij','fantasy',2.50)")
    mycursor.execute("insert into title(ISBN,title_name,author,genre,rating) values(335,'Metro2034','Dmitrij Gluchovskij','fantasy',2.50)")
    mycursor.execute("insert into title(ISBN,title_name,author,genre,rating) values(336,'Metro2035','Dmitrij Gluchovskij','fantasy',2.50)")
    mycursor.execute("insert into title(ISBN,title_name,author,genre,rating) values(337,'Ako Stefan Drco vyhral kopu hnoja. Rozhodni sa! - Cnosti.','Branislav Jobus','romanticka',2.50)")
    mycursor.execute("insert into title(ISBN,title_name,author,genre,rating) values(338,'Cesta domov','Sebastian Fitzek','romanticka',2.50)")
    mycursor.execute("insert into title(ISBN,title_name,author,genre,rating) values(111,'Cerv','František Kozmon','romanticka',2.50)")
    mycursor.execute("insert into title(ISBN,title_name,author,genre,rating) values(231,'Hriesne bohaty','Meghan March','romanticka',2.50)")
    mycursor.execute("insert into title(ISBN,title_name,author,genre,rating) values(434,'Institucia','Stephen King','romanticka',2.50)")
    mycursor.execute("insert into title(ISBN,title_name,author,genre,rating) values(444,'Jedina','Jorn Lier Horst','romanticka',2.50)")
    mycursor.execute("insert into title(ISBN,title_name,author,genre,rating) values(445,'Len raz','Ivana Popluharova','romanticka',2.50)")
    mycursor.execute("insert into title(ISBN,title_name,author,genre,rating) values(446,'Maly princ','De Saint Exupery','romanticka',2.50)")
    mycursor.execute("insert into title(ISBN,title_name,author,genre,rating) values(447,'Na zelanie krala','Kristína Brestenska','romanticka',2.50)")
    mycursor.execute("insert into title(ISBN,title_name,author,genre,rating) values(474,'Rad','Daniel Silva','romanticka',2.50)")
    mycursor.execute("insert into title(ISBN,title_name,author,genre,rating) values(454,'Rosnicka','Frantisek Kozmon','romanticka',2.50)")
    mycursor.execute("insert into title(ISBN,title_name,author,genre,rating) values(464,'Skore','Elle Kennedy','romanticka',2.50)")
    mycursor.execute("insert into title(ISBN,title_name,author,genre,rating) values(477,'Sedem hriesnych noci','Anna Campbell','romanticka',2.50)")
    mycursor.execute("insert into title(ISBN,title_name,author,genre,rating) values(478,'Vlk a dyka','Juraj Cervenak','detektivka',2.50)")
    mycursor.execute("insert into title(ISBN,title_name,author,genre,rating) values(479,'Vlk','František Kozmon','detektivka',2.50)")
    mycursor.execute("insert into title(ISBN,title_name,author,genre,rating) values(550,'Volavka','František Kozmon','detektivka',2.50)")
    mycursor.execute("insert into title(ISBN,title_name,author,genre,rating) values(505,'Cas opovrhnutia','Andrzej Sapkowski','fantasy',2.50)")
    mycursor.execute("insert into title(ISBN,title_name,author,genre,rating) values(525,'Krst ohnom','Andrzej Sapkowski','fantasy',2.50)")
    mycursor.execute("insert into title(ISBN,title_name,author,genre,rating) values(551,'Pani jazera','Andrzej Sapkowski','fantasy',2.50)")
    mycursor.execute("insert into title(ISBN,title_name,author,genre,rating) values(515,'Veza lastovicky','Andrzej Sapkowski','fantasy',2.50)")
    mycursor.execute("insert into title(ISBN,title_name,author,genre,rating) values(523,'Burkova sezona','Andrzej Sapkowski','fantasy',2.50)")
    mycursor.execute("insert into title(ISBN,title_name,author,genre,rating) values(532,'Ziarlivec','Jo Nesbo','detektivka',2.50)")
    mycursor.execute("insert into title(ISBN,title_name,author,genre,rating) values(533,'Zrada','Jo Nesbo','detektivka',2.50)")

    mycursor.execute("insert into book(ISBN,l_id,active) values(555,1,0)")
    mycursor.execute("insert into book(ISBN,l_id,active) values(555,1,1)")
    mycursor.execute("insert into book(ISBN,l_id,active) values(123,1,1)")
    mycursor.execute("insert into book(ISBN,l_id,active) values(123,3,1)")
    mycursor.execute("insert into book(ISBN,l_id,active) values(334,3,1)")
    mycursor.execute("insert into book(ISBN,l_id,active) values(335,3,1)")
    mycursor.execute("insert into book(ISBN,l_id,active) values(336,1,1)")
    mycursor.execute("insert into book(ISBN,l_id,active) values(231,3,1)")
    mycursor.execute("insert into book(ISBN,l_id,active) values(231,3,1)")
    mycursor.execute("insert into book(ISBN,l_id,active) values(444,3,1)")
    mycursor.execute("insert into book(ISBN,l_id,active) values(444,3,1)")
    mycursor.execute("insert into book(ISBN,l_id,active) values(479,1,1)")
    mycursor.execute("insert into book(ISBN,l_id,active) values(479,1,1)")
    mycursor.execute("insert into book(ISBN,l_id,active) values(505,3,1)")
    mycursor.execute("insert into book(ISBN,l_id,active) values(525,3,1)")
    mycursor.execute("insert into book(ISBN,l_id,active) values(523,1,1)")
    mycursor.execute("insert into book(ISBN,l_id,active) values(523,3,1)")
    mycursor.execute("insert into book(ISBN,l_id,active) values(515,3,1)")
    mycursor.execute("insert into book(ISBN,l_id,active) values(551,1,1)")

    mycursor.execute("insert into loan(b_id,u_id,d_from,d_to,l_id) values(1,1,DATE '2021-10-05',DATE '2022-10-05',1)")

    mycursor.execute("insert into book_order(ISBN,l_id,count) values(555,1,7)")
    mycursor.execute("insert into book_order(ISBN,l_id,count) values(123,3,3)")   

    mycursor.execute("insert into offers(ISBN,l_id, votes) values(555,1,0)")
    mycursor.execute("insert into offers(ISBN,l_id, votes) values(123,1,0)")
    mycursor.execute("insert into offers(ISBN,l_id, votes) values(123,3,0)")
    mycursor.execute("insert into offers(ISBN,l_id, votes) values(555,1,0)")
    mycursor.execute("insert into offers(ISBN,l_id, votes) values(555,1,0)")
    mycursor.execute("insert into offers(ISBN,l_id, votes) values(123,1,0)")
    mycursor.execute("insert into offers(ISBN,l_id, votes) values(123,3,0)")
    mycursor.execute("insert into offers(ISBN,l_id, votes) values(334,3,0)")
    mycursor.execute("insert into offers(ISBN,l_id, votes) values(335,3,0)")
    mycursor.execute("insert into offers(ISBN,l_id, votes) values(336,1,0)")
    mycursor.execute("insert into offers(ISBN,l_id, votes) values(231,3,0)")
    mycursor.execute("insert into offers(ISBN,l_id, votes) values(231,3,0)")
    mycursor.execute("insert into offers(ISBN,l_id, votes) values(444,3,1)")
    mycursor.execute("insert into offers(ISBN,l_id, votes) values(444,3,1)")
    mycursor.execute("insert into offers(ISBN,l_id, votes) values(479,1,1)")
    mycursor.execute("insert into offers(ISBN,l_id, votes) values(479,1,1)")
    mycursor.execute("insert into offers(ISBN,l_id, votes) values(505,3,1)")
    mycursor.execute("insert into offers(ISBN,l_id, votes) values(525,3,1)")
    mycursor.execute("insert into offers(ISBN,l_id, votes) values(523,1,1)")
    mycursor.execute("insert into offers(ISBN,l_id, votes) values(523,3,1)")
    mycursor.execute("insert into offers(ISBN,l_id, votes) values(515,3,1)")
    mycursor.execute("insert into offers(ISBN,l_id, votes) values(551,1,1)")

    db.commit()
    
def print_tables(db):
    mycursor = db.cursor()
    mycursor.execute("SHOW TABLES")
    print("Tabulky v databaze")
    for x in mycursor:
        print(x[0],end=",")
    print()
    print()
    mycursor.execute("SELECT * FROM library")
    print("Kniznice")
    for x in mycursor:
        print(x)
    print()
    mycursor.execute("SELECT * FROM title")
    print("tituly")
    for x in mycursor:
        print(x)
    print()
    mycursor.execute("SELECT * FROM book")
    print("knihy")
    for x in mycursor:
        print(x)
    print()
    mycursor.execute("SELECT * FROM user")
    print("citatelia")
    for x in mycursor:
        print(x)
    print()
    mycursor.execute("SELECT * FROM loan")
    print("vypozicky")
    for x in mycursor:
        print(x)
    print()
    mycursor.execute("SELECT * FROM book_order")
    print("objednavky")
    for x in mycursor:
        print(x)
    print()
    mycursor.execute("SELECT * FROM offers")
    print("ponuky")
    for x in mycursor:
        print(x)
    mycursor.execute("SELECT * FROM voted")
    print("hlasy")
    for x in mycursor:
        print(x)
    mycursor.execute("SELECT * FROM waiting")
    print("cakajuci vo fronte")
    for x in mycursor:
        print(x)
    

mydb = mysql.connector.connect(host='eva.fit.vutbr.cz', user='xbegan01', password='darze4so', database='xbegan01', unix_socket='/var/run/mysql/mysql.sock', port=0)
create_tables(mydb)
print_tables(mydb)
